/**
 * RosterSync.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RosterEvent { 
    id?: number;
    user_id?: number;
    type?: string;
    flight_number?: string | null;
    aircraft?: string | null;
    origin?: string | null;
    destination?: string | null;
    start_time?: string;
    end_time?: string;
    status?: string;
    created_at?: string;
    description?: string | null;
}

