/**
 * RosterSync.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LinkType } from './linkType';


export interface SyncConfigDto {
    id: number;
    calendarName: string;
    rosterUrl: string;
    linkType: LinkType;
    isActive: boolean;
    lastSync: string | null;
    phoneNumber: string | null;
}

